"""empty message

Revision ID: 3cc830af1fd3
Revises: 
Create Date: 2020-12-09 00:47:02.960057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cc830af1fd3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Admin_id'], ['Admin.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('film_hall',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['Film.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['Hall.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'hall_id')
    )
    op.create_table('film_timetable',
    sa.Column('film_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['film_id'], ['Film.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['Timetable.id'], ),
    sa.PrimaryKeyConstraint('film_id', 'timetable_id')
    )
    op.create_table('hall_timetable',
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['hall_id'], ['Hall.id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['Timetable.id'], ),
    sa.PrimaryKeyConstraint('hall_id', 'timetable_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall_timetable')
    op.drop_table('film_timetable')
    op.drop_table('film_hall')
    op.drop_table('Timetable')
    op.drop_table('Hall')
    op.drop_table('Film')
    op.drop_table('Admin')
    # ### end Alembic commands ###
