"""empty message

Revision ID: 53909d851594
Revises: 
Create Date: 2020-12-20 16:53:11.516245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53909d851594'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('firstname', sa.String(length=255), nullable=False),
    sa.Column('lastname', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Film',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Hall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('opacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Timetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('num_of_record', sa.Integer(), nullable=False),
    sa.Column('film_id', sa.Integer(), nullable=True),
    sa.Column('hall_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['film_id'], ['Film.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['Hall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Timetable')
    op.drop_table('Hall')
    op.drop_table('Film')
    op.drop_table('Admin')
    # ### end Alembic commands ###
